name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        dc: [dmd-latest, ldc-latest, dmd-2.085.0, ldc-1.17.0]
        exclude:
          - { os: macOS-latest, dc: dmd-2.085.0 }

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}
    - name: make tree-query
      run: (which dmd && make && echo "Built successfully with DMD Reference Compiler!") || true
    - name: make tree-query-build
      run: (which ldc2 && make tree-query-build && echo "Built successfully with LLVM D Compiler!") || true
    #- name: make distcheck
    #  run: make distcheck
